### ISSUE TITLE
個別DM検証の件

### ISSUE THREAD

**Issue by eRy-sk** [pmo23/basketball#2]
最新のブランチがプッシュされ次第検証します。

**Comment by eRy-sk** [comment]
@pmo23 
手元で動かしてみましたがDMページをroom_idで分けるところ
(Qiitaで提示していただいたソースコード)までpushされてないみたいですね。
そちらプッシュされ次第検証しますのでこちらにメンションをつけて連絡してください。

**Comment by pmo23** [comment]
@eRy-sk 
さんコードプッシュしました。

**Comment by pmo23** [comment]
マイグレーションファイルの件確かに、モデルの構築を最初にしっかりするべきでした。
ご指摘ありがとうございます。

**Comment by eRy-sk** [comment]
@pmo23 
マイグレーションエラーが解決できないと検証できません(´・ω・｀)
エラーが出ないよう修正してください。
`$ rails db:migrate`で確認してください。

**Comment by pmo23** [comment]
rails db:migrateしてもエラーにはならないんですが、どうすればよろしいですか

**Comment by eRy-sk** [comment]
@pmo23 
すでに実行済みだからもう実行されないのか...
`add_to_index_message.rb`と`remove_sent_id_message_from_message.rb`が存在しないカラムに作用しているので発生しているエラーなんですが...
一回DBリセットすれば再現するんですけどデータ全部消えるのは気が引けますし...
とりあえず問題のファイルを消して手元で動きはするんですが
`schema.rb`に差異があると面倒なのでそちらでも消してもらってpushしてもらえますか？
push権限もらえれば別ブランチにプルリク投げてそちらで作業できるんですけど...。

**Comment by eRy-sk** [comment]
もし都道府県以外のデータが一旦消えてもよければDBの再構築をお願いします。
都道府県のデータだけはseedファイル作ったので復元可能です。

**Comment by pmo23** [comment]
プッシュしました。

**Comment by pmo23** [comment]
push権限はどうすれば与えれますか？
ほんと知識不足ですいません。

**Comment by eRy-sk** [comment]
@pmo23 
リポジトリの設定(Settings)で設定画面に移動し、左のリストのCollaboratorsから追加できます。
「@eRy-sk」か僕のemailで追加できると思います。
うまくいかなければこちらの設定がうまくいってないので教えてください。

**Comment by pmo23** [comment]
追加できました！

**Comment by pmo23** [comment]
@eRy-sk 
コンフリクトを解消してマージしました。
プルして、DBをドロップして、再構築していけばよろしいでしょうか？
