### ISSUE TITLE
rooms#showについての質問

### ISSUE THREAD

**Issue by eRy-sk** [pmo23/basketball#4]
https://github.com/pmo23/basketball/blob/edf68ac8fa2451f5ac0df5e43b4e8b70975bc6c7/app/controllers/rooms_controller.rb#L4
https://github.com/pmo23/basketball/blob/edf68ac8fa2451f5ac0df5e43b4e8b70975bc6c7/app/controllers/rooms_controller.rb#L5
同じパラメータを参照しているみたいですが明らかに挙動がおかしいです。
ここの`params[:id]`は何の値を想定していますか？
(部屋のIDなのかユーザーのIDなのか)

**Comment by pmo23** [comment]
部屋のidをとりたいんですが、そもそも部屋がない状態です。

**Comment by eRy-sk** [comment]
なんとなくやりたいことはわかりました。
まず、ルームの作成についでですが、ユーザー間１対１のDMのみで使うのであれば
リクエストの関係を持っているモデルに紐付けるのがいいかと思います。

どうでしょうか？

**Comment by eRy-sk** [comment]
@pmo23 
なんとなくやりたいことはわかりました。
まず、ルームの作成についでですが、ユーザー間１対１のDMのみで使うのであれば
リクエストの関係を持っているモデルに紐付けるのがいいかと思います。

どうでしょうか？

**Comment by eRy-sk** [comment]
具体的な処理はDMリンクを踏んだ際にcurrent_userのIDとDMするユーザのIDを送信し、
コントローラ側で両者のIDを持つrelationshipsレコードを取得、
そこに紐づくroomがあればそのroomのIDを取得、なければ作成してIDを取得という形です。

**Comment by pmo23** [comment]
理解はできましたが、難しい、
でも挑戦します！！

**Comment by pmo23** [comment]
@eRy-sk さん
検証お願いします。

**Comment by eRy-sk** [comment]
@pmo23 
すみません、変更点がよくわかりません...。
ブランチを切ってプルリクエストで投げてください。

**Comment by pmo23** [comment]
@eRy-sk さんも検証お願いしますという意味です。
僕の伝え方が悪かったです。すいません。

**Comment by pmo23** [comment]
@eRy-sk 
どうすればいいか全くわかりません。
手詰まりの状態です。

**Comment by eRy-sk** [comment]
@pmo23 
「どうすればいいか全くわからない」というのはあまりよくないですね...。
具体的にわからないポイントがわからないとこちらもアドバイスのしようがないです。
何がわからないのでしょうか？モデル同士の紐付けですか？
Railsの基礎的な部分でしたら日本語版のチュートリアルがありますので
そちらで学習されるのをお勧めします。
[Ruby on Rails Tutorial](https://railstutorial.jp/)

**Comment by pmo23** [comment]
DMリンクを踏んだ際にcurrent_userのIDとDMするユーザのIDを送信、のところまではできますが、その後の、roomがあるか、なければroomを作成という部分が、わかりません。

**Comment by eRy-sk** [comment]
その送信されたcurrent_userのIDとDMするユーザのIDをカラムに持つrelationshipsレコードを取得。
ここまではいいですかね？
そしてRoomモデルをRelationshipモデルに紐づけていれば
relationshipsレコードに紐づくroomレコードを取得(find)、なければ作成(create)...といった具合なんですが、これがすんなり分からない場合はやることがいくつかあります。

1. モデルの設計を見直す
   * 現在のモデルの設計を見直して、不要なもの、まとめるべきもの、分割すべきものはそのように修正するべきです
   * 現状問題があるということを言っているわけではないので修正しなくても良いという判断であればそれで構いません
   * とにかく現状のモデルの構造を理解し、何が何に関連を持っていて、今後追加するモデルは何に関連づけるべきかをしっかりと理解することが大切です。
   * どうすればいいか分からなければER図というものを書くといいと思います。ER図が分からなければ調べてみましょう。PCで作成するのは慣れないうちは難しいので手書きでいいです。

2. Roomモデルを作成し、適切なモデルに紐づける。
   * 今回はフォロー機能のようなものがあるみたいなのでそれに紐づけるのがいいかと思いますが、モデルの整理をした時、もっと適切なモデルがあると判断した場合はそれに紐づけるといいともいます。
   * 紐付けが分からないときは、基礎力がないということになってしまうので以前URL貼ったチュートリアルを開始するのがいいと思います。開発は中断してしまいますが、今後のことを考えると格段のスキルアップになりますし最も効率的です。

3. モデルを整理してRailsチュートリアルも理解できればすんなり実装できると思います。それでも分からなければ懇切丁寧に教えますので連絡ください。

**Comment by eRy-sk** [comment]
@pmo23 
その送信されたcurrent_userのIDとDMするユーザのIDをカラムに持つrelationshipsレコードを取得。
ここまではいいですかね？
そしてRoomモデルをRelationshipモデルに紐づけていれば
relationshipsレコードに紐づくroomレコードを取得(find)、なければ作成(create)...といった具合なんですが、これがすんなり分からない場合はやることがいくつかあります。

1. モデルの設計を見直す
   * 現在のモデルの設計を見直して、不要なもの、まとめるべきもの、分割すべきものはそのように修正するべきです
   * 現状問題があるということを言っているわけではないので修正しなくても良いという判断であればそれで構いません
   * とにかく現状のモデルの構造を理解し、何が何に関連を持っていて、今後追加するモデルは何に関連づけるべきかをしっかりと理解することが大切です。
   * どうすればいいか分からなければER図というものを書くといいと思います。ER図が分からなければ調べてみましょう。PCで作成するのは慣れないうちは難しいので手書きでいいです。

2. Roomモデルを作成し、適切なモデルに紐づける。
   * 今回はフォロー機能のようなものがあるみたいなのでそれに紐づけるのがいいかと思いますが、モデルの整理をした時、もっと適切なモデルがあると判断した場合はそれに紐づけるといいともいます。
   * 紐付けが分からないときは、基礎力がないということになってしまうので以前URL貼ったチュートリアルを開始するのがいいと思います。開発は中断してしまいますが、今後のことを考えると格段のスキルアップになりますし最も効率的です。

3. モデルを整理してRailsチュートリアルも理解できればすんなり実装できると思います。それでも分からなければ懇切丁寧に教えますので連絡ください。

**Comment by pmo23** [comment]
@eRy-sk 
roomモデルとrelationshipモデルをhas_oneとbelongs_toで１対１の関係にして、relationshipモデルにroom_idカラムを追加しました。
またroom_usersテーブルを削除しました。

**Comment by eRy-sk** [comment]
@pmo23 
> roomモデルとrelationshipモデルをhas_oneとbelongs_toで１対１の関係にして、relationshipモデルにroom_idカラムを追加しました。

逆ですね、Relationshipモデルを親とするのが適当だと思います。

> room_usersテーブルを削除しました。

きちんと削除しないとまたマイグレーションエラーが起きたりするので気をつけてくださいね。

以後変更内容についてはプルリクでメンションを投げてくれるとレビューもしやすいのでそれでお願いします。

**Comment by eRy-sk** [comment]
不要になったらCloseしてください。
